export default Object.freeze({
  data: {
    users: [
      {
        name: 'test one',
        picture: 'https://placehold.co/400',
        username: 'testone',
        xp: 50,
      },
      {
        name: 'test two',
        picture: 'https://placehold.co/400',
        username: 'testtwo',
        xp: 200,
      },
      {
        name: 'John Doe',
        picture: 'https://placehold.co/400',
        username: 'johndoe',
        xp: 400,
      },
      {
        name: 'Jane Smith',
        picture: 'https://placehold.co/400',
        username: 'janesmith',
        xp: 120,
      },
      {
        name: 'Bob Johnson',
        picture: 'https://placehold.co/400',
        username: 'bobjohnson',
        xp: 300,
      },
      {
        name: 'Sarah Lee',
        picture: 'https://placehold.co/400',
        username: 'sarahlee',
        xp: 620,
      },
      {
        name: 'Mark Davis',
        picture: 'https://placehold.co/400',
        username: 'markdavis',
        xp: 700,
      },
      {
        name: 'Emily Jones',
        picture: 'https://placehold.co/400',
        username: 'emilyjones',
        xp: 175,
      },
      {
        name: 'Tom Wilson',
        picture: 'https://placehold.co/400',
        username: 'tomwilson',
        xp: 225,
      },
      {
        name: 'Mary Brown',
        picture: 'https://placehold.co/400',
        username: 'marybrown',
        xp: 125,
      },
      {
        name: 'David Lee',
        picture: 'https://placehold.co/400',
        username: 'davidlee',
        xp: 190,
      },
      {
        name: 'Karen Davis',
        picture: 'https://placehold.co/400',
        username: 'karendavis',
        xp: 280,
      },
      {
        name: 'Joe Johnson',
        picture: 'https://placehold.co/400',
        username: 'joejohnson',
        xp: 150,
      },
      {
        name: 'Amy Chen',
        picture: 'https://placehold.co/400',
        username: 'amychen',
        xp: 225,
      },
      {
        name: 'Chris Lee',
        picture: 'https://placehold.co/400',
        username: 'chrislee',
        xp: 175,
      },
      {
        name: 'Linda Davis',
        picture: 'https://placehold.co/400',
        username: 'lindadavis',
        xp: 300,
      },
      {
        name: 'Mike Smith',
        picture: 'https://placehold.co/400',
        username: 'mikesmith',
        xp: 200,
      },
      {
        name: 'Samantha Lee',
        picture: 'https://placehold.co/400',
        username: 'samanthalee',
        xp: 275,
      },
      {
        name: 'Alex Johnson',
        picture: 'https://placehold.co/400',
        username: 'alexjohnson',
        xp: 250,
      },
      {
        name: 'Olivia Brown',
        picture: 'https://placehold.co/400',
        username: 'oliviabrown',
        xp: 190,
      },
      {
        name: 'Jake Davis',
        picture: 'https://placehold.co/400',
        username: 'jakedavis',
        xp: 125,
      },
    ],
  },
})
