export default Object.freeze({
  data: [
    {
      bio: 'asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj',
      firstName: 'test',
      name: 'test one',
      profilePicture: 'https://placehold.co/400',
      username: 'testone',
      xp: 50,
    },
    {
      bio: 'asd asd sadasd wahsjdkhsjadsja hdsajdhj asd',
      firstName: 'test',
      name: 'test three',
      profilePicture: 'https://placehold.co/400',
      username: 'testthree',
      xp: 560,
    },
    {
      bio: 'asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj',
      firstName: 'John',
      name: 'John Doe',
      profilePicture: 'https://placehold.co/400',
      username: 'johndoe',
      xp: 400,
    },
    {
      bio: 'asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj',
      firstName: 'test',
      name: 'test two',
      profilePicture: 'https://placehold.co/400',
      username: 'testtwo',
      xp: 200,
    },
    {
      bio: 'asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj',
      firstName: 'Jane',
      name: 'Jane Smith',
      profilePicture: 'https://placehold.co/400',
      username: 'janesmith',
      xp: 120,
    },
    {
      bio: 'asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja',
      firstName: 'Bob',
      name: 'Bob Johnson',
      profilePicture: 'https://placehold.co/400',
      username: 'bobjohnson',
      xp: 300,
    },
    {
      bio: 'asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj asd asd sadasd wahsjdkhsjadsja hdsajdhj',
      firstName: 'Sarah',
      name: 'Sarah Lee',
      profilePicture: 'https://placehold.co/400',
      username: 'sarahlee',
      xp: 620,
    },
  ],
})
