# base image
FROM node:18-alpine

# set working directory
WORKDIR /app

# copy package.json and package-lock.json
COPY package*.json ./

# install dependencies
RUN npm ci

# copy the rest of the application files
COPY . .

# build the application
RUN npm run build

# start the application
CMD ["npm", "run", "preview"]
