version: '3'

services:
  vite-dev-app:
    container_name: vite-dev-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    env_file:
      - ../env/.env.development.local
    environment:
      - MODE="development"
      - VITE_API_URL=${VITE_API_URL}
      - VITE_MODE=${VITE_MODE}
    ports:
      - 3000:3000
    networks:
      - vite_network

networks:
  vite_network:
    external: false
    name: 'vite_network'
