# base image
FROM node:18-alpine

# set working directory
WORKDIR /app

# copy package.json and package-lock.json
COPY package*.json ./

# install dependencies
RUN npm install

# copy the rest of the application files
COPY . .

# start the application
CMD ["npm", "run", "dev"]
