export default Object.freeze({
  data: {
    sun: {
      morning: {
        category: 'AEROBIC',
        checked: false,
        classification: 'BRONZE',
        description:
          'Quest 1 description Quest 1 description Quest 1 descriptionQuest 1 description Quest 1 description Quest 1 descriptionQuest 1 description Quest 1 description Quest 1 description Quest 1 description',
        duration: 13,
        id: '1',
        name: 'Quest 1',
        xp: 80,
        exercises: [
          'ex 1 ex 1 ex 1 ex 1 ex 1 ex 1ex 1 ex 1 ex 1 ex 1 ex 1 ex 1ex 1 ex 1 ex 1 ex 1 ex 1 ex 1ex 1 ex 1 ex 1 ex 1 ex 1 ex 1ex 1 ex 1 ex 1 ex 1 ex 1 ex 1ex 1 ex 1 ex 1 ex 1 ex 1 ex 1ex 1 ex 1 ex 1 ex 1 ex 1 ex 1ex 1 ex 1 ex 1 ex 1 ex 1 ex 1ex 1 ex 1 ex 1 ex 1 ex 1 ex 1ex 1 ex 1 ex 1 ex 1 ex 1 ex 1ex 1 ex 1 ex 1 ex 1 ex 1 ex 1ex 1 ex 1 ex 1 ex 1 ex 1 ex 1',
          'ex 2',
          'ex 2',
          'ex 2',
        ],
      },
      afternoon: null,
      night: null,
    },
    mon: {
      morning: {
        category: 'FLEXIBILITY',
        checked: false,
        classification: 'BRONZE',
        description: 'Quest 1 description',
        duration: 13,
        id: '1',
        name: 'Quest 1',
        xp: 80,
        exercises: ['ex 1', 'ex 2'],
      },
      afternoon: null,
      night: null,
    },
    tue: {
      morning: {
        category: 'STRENGTH',
        checked: false,
        classification: 'BRONZE',
        description: 'Quest 1 description',
        duration: 13,
        id: '1',
        name: 'Quest 1',
        xp: 80,
        exercises: ['ex 1', 'ex 2'],
      },
      afternoon: null,
      night: null,
    },
    wed: {
      morning: null,
      afternoon: {
        category: 'FLEXIBILITY',
        checked: false,
        classification: 'BRONZE',
        description: 'Quest 1 description',
        duration: 13,
        id: '1',
        name: 'Quest 1',
        xp: 80,
        exercises: ['ex 1', 'ex 2'],
      },
      night: null,
    },
    thu: {
      morning: null,
      afternoon: null,
      night: {
        category: 'ANAEROBIC',
        checked: false,
        classification: 'BRONZE',
        description: 'Quest 1 description',
        duration: 13,
        id: '1',
        name: 'Quest 1',
        xp: 80,
        exercises: ['ex 1', 'ex 2'],
      },
    },
    fri: {
      morning: null,
      afternoon: {
        category: 'ANAEROBIC',
        checked: false,
        classification: 'BRONZE',
        description: 'Quest 1 description',
        duration: 13,
        id: '1',
        name: 'Quest 1',
        xp: 80,
        exercises: ['ex 1', 'ex 2'],
      },
      night: {
        category: 'AEROBIC',
        checked: false,
        classification: 'BRONZE',
        description: 'Quest 1 description',
        duration: 13,
        id: '1',
        name: 'Quest 1',
        xp: 80,
        exercises: ['ex 1', 'ex 2'],
      },
    },
    sat: {
      morning: null,
      afternoon: {
        category: 'STRENGTH',
        checked: false,
        classification: 'BRONZE',
        description: 'Quest 1 description',
        duration: 13,
        id: '1',
        name: 'Quest 1',
        xp: 80,
        exercises: ['ex 1', 'ex 2'],
      },
      night: null,
    },
  },
  status: 200,
})
