export default Object.freeze({
  data: [
    {
      id: '1',
      category: 'AEROBIC',
      duration: 18,
      name: 'Quest 1',
      trainingDay: {
        dayOfWeek: 'sun',
        period: 'morning',
      },
      exercises: ['ex 1'],
      status: 'uncompleted',
      xp: 80,
      unlockXp: 80,
    },
    {
      id: '2',
      category: 'AEROBIC',
      duration: 24,
      name: 'Quest 2',
      trainingDay: {
        dayOfWeek: 'sun',
        period: 'afternoon',
      },
      exercises: ['ex 1'],
      status: 'finished',
      xp: 40,
      unlockXp: 380,
    },
    {
      id: '3',
      category: 'STRENGTH',
      duration: 8,
      name: 'Quest 3',
      trainingDay: {
        dayOfWeek: 'sun',
        period: 'night',
      },
      exercises: ['ex 1', 'ex 2'],
      status: 'pending',
      xp: 20,
      unlockXp: 100,
    },
    // mon: {
    //   morning: {
    //     category: 'FLEXIBILITY',
    //     checked: false,
    //     classification: 'BRONZE',
    //     description: 'Quest 1 description',
    //     duration: 13,
    //     id: '1',
    //     name: 'Quest 1',
    //     xp: 80,
    //     exercises: ['ex 1', 'ex 2'],
    //   },
    //   afternoon: null,
    //   night: null,
    // },
    // tue: {
    //   morning: {
    //     category: 'STRENGTH',
    //     checked: false,
    //     classification: 'BRONZE',
    //     description: 'Quest 1 description',
    //     duration: 13,
    //     id: '1',
    //     name: 'Quest 1',
    //     xp: 80,
    //     exercises: ['ex 1', 'ex 2'],
    //   },
    //   afternoon: null,
    //   night: null,
    // },
    // wed: {
    //   morning: null,
    //   afternoon: {
    //     category: 'FLEXIBILITY',
    //     checked: false,
    //     classification: 'BRONZE',
    //     description: 'Quest 1 description',
    //     duration: 13,
    //     id: '1',
    //     name: 'Quest 1',
    //     xp: 80,
    //     exercises: ['ex 1', 'ex 2'],
    //   },
    //   night: null,
    // },
    // thu: {
    //   morning: null,
    //   afternoon: null,
    //   night: {
    //     category: 'ANAEROBIC',
    //     checked: false,
    //     classification: 'BRONZE',
    //     description: 'Quest 1 description',
    //     duration: 13,
    //     id: '1',
    //     name: 'Quest 1',
    //     xp: 80,
    //     exercises: ['ex 1', 'ex 2'],
    //   },
    // },
    // fri: {
    //   morning: null,
    //   afternoon: {
    //     category: 'ANAEROBIC',
    //     checked: false,
    //     classification: 'BRONZE',
    //     description: 'Quest 1 description',
    //     duration: 13,
    //     id: '1',
    //     name: 'Quest 1',
    //     xp: 80,
    //     exercises: ['ex 1', 'ex 2'],
    //   },
    //   night: {
    //     category: 'AEROBIC',
    //     checked: false,
    //     classification: 'BRONZE',
    //     description: 'Quest 1 description',
    //     duration: 13,
    //     id: '1',
    //     name: 'Quest 1',
    //     xp: 80,
    //     exercises: ['ex 1', 'ex 2'],
    //   },
    // },
    // sat: {
    //   morning: null,
    //   afternoon: {
    //     category: 'STRENGTH',
    //     checked: false,
    //     classification: 'BRONZE',
    //     description: 'Quest 1 description',
    //     duration: 13,
    //     id: '1',
    //     name: 'Quest 1',
    //     xp: 80,
    //     exercises: ['ex 1', 'ex 2'],
    //   },
    //   night: null,
    // },
  ],
  status: 200,
})
